package com.example.mesonstechinterviewproject.persistence.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.List;


@DynamoDBTable(tableName = "MesonsTechInterviewProjectApplication")
@Data
public class Task {

    public Task() {
        this.title = null;
        this.description = null;
        this.status = null;
        this.dueDate=null;
    }

    public Task(String title, List<String> description, List<String> status, String dueDate) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.dueDate = dueDate;
    }

    @DynamoDBHashKey(attributeName ="Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Title")
    private String title;

    @DynamoDBAttribute(attributeName = "Description")
    private List<String> description;                   //since DynamoDB is non-relational, users can put as many array as possible

    @DynamoDBAttribute(attributeName = "Status")
    private List<String> status;

    @DynamoDBAttribute(attributeName = "DueDate")
    private String dueDate;

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(List<String> description1) {
        this.description = description1;
    }

    public List<String> getDescription(List<String> description) {
        return description;
    }

    public void setStatus(List<String> status) {
        this.status = status;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }


}
